services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - app-network
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=myuser
    ports:
      - "5432:5432"
    networks:
      - app-network
  redis:
    build:
      context: .
      dockerfile: Dockerfile_cache
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
